-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgT2tfhNdYqsJFCcpX
qZ9IHGgt9sXErR7FXlyIqxMb9rOgCgYIKoZIzj0DAQehRANCAAT1S93jP3SwZsod
ucoq2XO0CIqMOVq4AUKzP2a03f/5oB1iuEhMqq5Xo/p6xCkadyJwmWu6dYXO/psG
rrtzLQnL
-----END PRIVATE KEY-----