import { memo } from 'react';
import { Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Apple App Store / user transparency notice for AI features.
 * Keep this visible near every entry point that sends text to a generative model.
 */
export const AI_PROVIDER_LABEL = 'Llama 3.3 (via Groq)';
export const AI_PROVIDER_FALLBACKS = 'Google Gemini, Moonshot & MiniMax';

interface AIDisclosureProps {
  isLight?: boolean;
  /** compact = one line under search; roomy = chat footer / privacy */
  variant?: 'compact' | 'roomy';
  className?: string;
}

export const AIDisclosure = memo(function AIDisclosure({
  isLight = false,
  variant = 'compact',
  className,
}: AIDisclosureProps) {
  if (variant === 'roomy') {
    return (
      <div
        className={cn(
          'rounded-2xl border px-3.5 py-3 text-[11px] leading-relaxed',
          isLight
            ? 'bg-black/[0.03] border-black/10 text-black/55'
            : 'bg-white/[0.04] border-white/10 text-white/55',
          className,
        )}
        role="note"
        aria-label="AI disclosure"
      >
        <p className={cn('font-semibold mb-1 flex items-center gap-1.5', isLight ? 'text-black/70' : 'text-white/75')}>
          <Sparkles className="w-3.5 h-3.5 shrink-0 text-primary" aria-hidden />
          Powered by AI
        </p>
        <p>
          Replies are generated by artificial intelligence — primarily{' '}
          <span className={isLight ? 'text-black/75 font-medium' : 'text-white/80 font-medium'}>
            {AI_PROVIDER_LABEL}
          </span>
          , with secure fallbacks ({AI_PROVIDER_FALLBACKS}). Content may be inaccurate.
          Not a substitute for professional legal, real estate, or financial advice.
          Only your chat messages are sent to AI providers — not your password or payment data.
        </p>
      </div>
    );
  }

  return (
    <p
      className={cn(
        'w-full flex items-start gap-1.5 text-[10px] sm:text-[11px] leading-snug tracking-wide',
        isLight ? 'text-black/45' : 'text-white/45',
        className,
      )}
      role="note"
      aria-label="AI disclosure"
    >
      <Sparkles
        className={cn('w-3 h-3 shrink-0 mt-0.5', isLight ? 'text-black/40' : 'text-white/40')}
        aria-hidden
      />
      <span>
        <span className={cn('font-semibold', isLight ? 'text-black/55' : 'text-white/55')}>
          AI-powered
        </span>
        {' · '}
        Answers are generated by {AI_PROVIDER_LABEL}
        {' '}(fallbacks: Gemini, Moonshot, MiniMax). May be wrong — verify important decisions.
      </span>
    </p>
  );
});
