// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.generated';
// These are the project's PUBLIC keys (anon / publishable). They are safe to
// ship in the client bundle — they are exposed in every build regardless. We
// read them from the build-time env when available, but fall back to the known
// public values so a missing/mis-injected env var can NEVER blank the whole app
// (a top-level throw here kills the entire bundle and React never mounts).
const FALLBACK_SUPABASE_URL = 'https://vplgtcguxujxwrgguxqq.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_FA0BseFSS6zM7Y8K3w8zLQ_d8BXqEuV';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  // Non-fatal: warn but keep running on the public fallback so the app mounts.
  console.warn('[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY not set at build time — using public fallback.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      // Fetch with 30s timeout — prevent AI request timeouts while allowing for slower mobile networks
      fetch: (url: RequestInfo | URL, options?: RequestInit) => {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000); 
        return fetch(url, { ...options, signal: controller.signal })
          .finally(() => clearTimeout(timeoutId));
      },
    },
    realtime: {
      params: {
        eventsPerSecond: 20, // Increased from 10 for smoother real-time UX
      },
      // Explicit heartbeat + exponential reconnect backoff
      // Reduced heartbeat to 20s to detect drops faster on flaky networks (mobile)
      heartbeatIntervalMs: 20000,
      reconnectAfterMs: (tries: number) => {
        // Optimized backoff: 1s, 2s, 4s, 8s, 16s, then max 30s
        return Math.min(Math.pow(2, tries) * 1000, 30000);
      },
    },
  }
);



